from my_telegram.callbacks.ICallback import ICallback
from my_telegram.callbacks.asset_callback import AssetCallback
from my_telegram.callbacks.asset_callback_beta import AssetCallbackBeta
from my_telegram.callbacks.exchange_rate import ExchangeRateCallback
from my_telegram.callbacks.oil_price import OilPriceCallback
from my_telegram.callbacks.stock import StockCallback
